FROM --platform=linux/amd64 node:16-alpine

RUN set -eux \
  & apk add \
  --no-cache \
  yarn

WORKDIR /app

COPY ./package.json ./yarn.lock ./

RUN yarn install

COPY . .

RUN chmod a+x ./scripts/dev/api-entrypoint.sh

ENTRYPOINT [ "/app/scripts/dev/api-entrypoint.sh" ]