version: '3.8'
services:
  postgres:
    image: postgres:11
    container_name: pgdb
    env_file:
      - .env
    ports:
      - 5432:5432
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
  api:
    container_name: graphql-api
    build:
      context: ./
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src
      - ./test:/app/test
      - ./prisma:/app/prisma
    depends_on:
      - postgres